name: Node.js CI/CD
on:
  push:
    branches:
      - main
    pull_request:
      branches: [ "main" ]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          # password: ${{secrets.PASSWORD}}
          kays: ${{secrets.SSH_KEY}}
          script: |
            cd /home/vishnu/nodejsapp
            git pull origin main
            docker compose up -d --build